### ISSUE TITLE
Codesnippet issues on JDK 13 and JDK 14

### ISSUE THREAD

**Issue by JonathanGiles** [jtulach/codesnippet4javadoc#22]
I've noticed issues with CodeSnippet 0.53 and 0.54 when running on JDK 13 and JDK 14. The issues are slightly different depending on the CodeSnippet version.

On CodeSnippet 0.53, with JDK 13 and 14, I see the following output in my build (which then fails as the build is set to fail on warning and errors):

```sh
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project azure-core: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - error: no class output directory specified
[ERROR] CodesnippetDoclet: warning - File ignored: "/Users/jonathan/Code/azure/forks/azure-sdk-for-java/sdk/core/azure-core/src/main/java/module-info.java" (not yet supported)
[ERROR] /Users/jonathan/Code/azure/forks/azure-sdk-for-java/sdk/core/azure-core/src/main/java/com/azure/core/credential/SimpleTokenCache.java:4: error: not in a module on the module source path
[ERROR] package com.azure.core.credential;
```

(This list of classes carries on for every class in the module).

On CodeSnippet 0.54, with JDK 13 and 14, I see the following output in my build (which then fails):

```sh
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project azure-core: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - java.lang.IllegalStateException: Cannot call public void com.sun.tools.javac.main.Option.process(com.sun.tools.javac.main.OptionHelper,java.lang.String,java.lang.String) throws com.sun.tools.javac.main.Option$InvalidValueException with [com.sun.tools.oldlets.javadoc.main.Start$1@2cae1042, --patch-module, com.azure.core=/Users/jonathan/Code/azure/forks/azure-sdk-for-java/sdk/core/azure-core/src/main/java:/Users/jonathan/Code/azure/forks/azure-sdk-for-java/sdk/core/azure-core/target/generated-sources/annotations]
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.SymbolKind.invokeOrNull(SymbolKind.java:345)
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.ToolOption.processOption(ToolOption.java:463)
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.ToolOption$23.process(ToolOption.java:210)
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.Start.parseAndExecute(Start.java:311)
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.Start.begin(Start.java:232)
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.Start.begin(Start.java:225)
[ERROR] 	at org.apidesign.javadoc.codesnippet.Doclet.run(Doclet.java:392)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:552)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:396)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
[ERROR] Caused by: java.lang.reflect.InvocationTargetException
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.SymbolKind.invokeOrNull(SymbolKind.java:343)
[ERROR] 	... 11 more
[ERROR] Caused by: java.lang.IllegalArgumentException
[ERROR] 	at jdk.compiler/com.sun.tools.javac.main.OptionHelper$GrumpyHelper.handleFileManagerOption(OptionHelper.java:139)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.main.Option.process(Option.java:1205)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.main.Option$8.process(Option.java:248)
[ERROR] 	... 16 more
[ERROR] CodesnippetDoclet: error - fatal exception
[ERROR] javadoc: error - an unknown error has occurred
```

Any guidance would be hugely appreciated. Thanks!

**Comment by JonathanGiles** [comment]
@srnagar or I will provide a sample app to reproduce this issue in the coming days.

**Comment by srnagar** [comment]
I have a sample app to reproduce the error:

### Using the codesnippet doclet
Running `mvn clean install javadoc:javadoc` produces the above errors using JDK 14 and 13. We notice different errors using version 0.53 and 0.54.

https://github.com/srnagar/snippet-demo/tree/with-codesnippet


### Using the default JDK doclet
Javadoc generation succeeds using the default JDK doclet.
https://github.com/srnagar/snippet-demo/tree/jdk-default-doclet

**Comment by srnagar** [comment]
@jtulach any update on this?

**Comment by jtulach** [comment]
- pátek 15. května 2020 19:44:41 CEST, Srikanta -
> @jtulach any update on this?

I still haven't had time to take a look.

**Comment by jtulach** [comment]
- pátek 15. května 2020 19:44:41 CEST, Srikanta -
> @jtulach any update on this?

I am able to generate javadoc of your project, if I remove `module-info.java`.

**Comment by jtulach** [comment]
OK?
