### ISSUE TITLE
JavaDoc fails if doclint is set to 'all' under JDK 17

### ISSUE THREAD

**Issue by JonathanGiles** [jtulach/codesnippet4javadoc#24]
If my build has 'doclint' set to 'all' (in Maven in my case), I get the following error output:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.0:jar (attach-javadocs) on project test: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 4 - error: fatal error encountered: java.lang.IncompatibleClassChangeError: Expected static method 'boolean com.sun.tools.doclint.DocLint.isValidOption(java.lang.String)'
[ERROR] error: Please file a bug against the javadoc tool via the Java bug reporting page
[ERROR]   (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
[ERROR]   for duplicates. Include error messages and the following diagnostic in your report. Thank you.
[ERROR] java.lang.IncompatibleClassChangeError: Expected static method 'boolean com.sun.tools.doclint.DocLint.isValidOption(java.lang.String)'
[ERROR] 	at com.sun.tools.oldlets.formats.html.ConfigurationImpl.validOptions(ConfigurationImpl.java:512)
[ERROR] 	at com.sun.tools.oldlets.formats.html.HtmlDoclet.validOptions(HtmlDoclet.java:316)
[ERROR] 	at org.apidesign.javadoc.codesnippet.Doclet.validOptions(Doclet.java:297)
[ERROR] 	at org.apidesign.javadoc.codesnippet.Doclet$DelegatingOption.process(Doclet.java:221)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.consumeDocletOption(Start.java:630)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseArgs(Start.java:824)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:498)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:393)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
[ERROR] 2 errors
```

Removing the `<doclint>all</doclint>` line gets me past this issue.

**Comment by jtulach** [comment]
Fixed in version 0.62
