### ISSUE TITLE
Missing constructor in Log class causes NoSuchMethodError

### ISSUE THREAD

**Issue by JonathanGiles** [jtulach/codesnippet4javadoc#25]
Because of [this change](https://bugs.openjdk.java.net/browse/JDK-8267187), I get the following error message when running this doclet under JDK 17:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.0:jar (attach-javadocs) on project test: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 4 - error: fatal error encountered: java.lang.NoSuchMethodError: 'void com.sun.tools.javac.util.Log.<init>(com.sun.tools.javac.util.Context, java.io.PrintWriter, java.io.PrintWriter, java.io.PrintWriter)'
[ERROR] error: Please file a bug against the javadoc tool via the Java bug reporting page
[ERROR]   (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com)
[ERROR]   for duplicates. Include error messages and the following diagnostic in your report. Thank you.
[ERROR] java.lang.NoSuchMethodError: 'void com.sun.tools.javac.util.Log.<init>(com.sun.tools.javac.util.Context, java.io.PrintWriter, java.io.PrintWriter, java.io.PrintWriter)'
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.Messager.<init>(Messager.java:121)
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.Messager.<init>(Messager.java:105)
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.Start.<init>(Start.java:128)
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.Start.<init>(Start.java:122)
[ERROR] 	at com.sun.tools.oldlets.javadoc.main.Start.<init>(Start.java:138)
[ERROR] 	at org.apidesign.javadoc.codesnippet.Doclet.run(Doclet.java:393)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:556)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:393)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:342)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:63)
[ERROR] 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:52)
```

**Comment by jtulach** [comment]
Fixed in version 0.62
