### ISSUE TITLE
CodesnippetDoclet does not work on JDK-21

### ISSUE THREAD

**Issue by tzezula** [jtulach/codesnippet4javadoc#32]
CodesnippetDoclet crashes on JDK-21.

```
WARNING: stderr: java.lang.NoClassDefFoundError: com/sun/tools/javac/main/CommandLine
WARNING: stderr: 	at com.sun.tools.oldlets.javadoc.main.Start.parseAndExecute(Start.java:282)
WARNING: stderr: 	at com.sun.tools.oldlets.javadoc.main.Start.begin(Start.java:234)
WARNING: stderr: 	at com.sun.tools.oldlets.javadoc.main.Start.begin(Start.java:227)
WARNING: stderr: 	at org.apidesign.javadoc.codesnippet.Doclet.run(Doclet.java:430)
WARNING: stderr: 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:575)
WARNING: stderr: 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:398)
WARNING: stderr: 	at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:347)
WARNING: stderr: 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.execute(Main.java:57)
WARNING: stderr: 	at jdk.javadoc/jdk.javadoc.internal.tool.Main.main(Main.java:46)
WARNING: stderr: Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.main.CommandLine
WARNING: stderr: 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
WARNING: stderr: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
WARNING: stderr: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
WARNING: stderr: 	... 9 more
WARNING: stderr: CodesnippetDoclet: error - fatal error
WARNING: stderr: error: an unknown error has occurred
WARNING: stderr: 1 error
```

**Comment by tzezula** [comment]
Verified, woks fine.
